import Head from 'next/head'
import DashboardLayout from '../../components/layout/DashboardLayout'
import { Table, Text } from '@mantine/core'
import { Device } from '@prisma/client';
import { useEffect, useState } from 'react';
import axios from "axios";

export default function DeviceList() {
  const ths = (
    <tr>
      <th>Id</th>
      <th>User Id</th>
      <th>device Id</th>
      <th>latitude</th>
      <th>longtitude</th>
      <th>Created At</th>
      <th>Updated At</th>
    </tr>
  );

  const [devices, setDevices] = useState([]);

  useEffect(() => {
    const getData = async () => {
      const { data } = await axios.get("/api/devices");
      setDevices(data);
    }
  })


  const rows = devices.map((element: Device) => (
    <tr key={element.id}>
      <td>{element.userId}</td>
      <td>{element.deviceId}</td>
      <td>{element.latitude}</td>
      <td>{element.longtitude}</td>
      <td>{new Date(element.createdAt).toLocaleDateString()}</td>
      <td>{new Date(element.updatedAt).toLocaleDateString()}</td>
    </tr>
  ));

  return (
    <>
      <Head>
        <title>Mutluluk Endeksi | Device List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DashboardLayout>
          <Table striped highlightOnHover withBorder withColumnBorders>
            <caption>Device List</caption>
            <thead>{ths}</thead>
            <tbody>{rows}</tbody>
            <tfoot>{ths}</tfoot>
          </Table>
        </DashboardLayout>
      </main>
    </>
  )
}
