import Head from 'next/head'
import DashboardLayout from '../../components/layout/DashboardLayout'
import { Card, Center, Group, Pagination, ScrollArea, Table, Text } from '@mantine/core'
import { useEffect, useState } from 'react';
import axios from 'axios';
import { User } from '.prisma/client';

export default function UserList() {
  const ths = (
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Email</th>
      <th>Email Verified</th>
      <th>Image</th>
      <th>Password</th>
      <th>CreatedAt</th>
      <th>UpdatedAt</th>
    </tr>
  );

  const [users, setUsers] = useState([]);
  const [activePage, setPage] = useState(1);

  useEffect(() => {
    const getData = async () => {
      const { data } = await axios.get("/api/users");
      setUsers(data);
    }

    getData()
  })

  const rows = users.map((element: User) => (
    <tr key={element.id}>
      <td>{element.id}</td>
      <td>{element.name}</td>
      <td>{element.email}</td>
      {/* @ts-ignore */}
      <td>{new Date(element.emailVerified).toLocaleDateString()}</td>
      <td>{element.image}</td>
      <td>{element.password}</td>
      <td>{new Date(element.createdAt).toLocaleDateString()}</td>
      <td>{new Date(element.updatedAt).toLocaleDateString()}</td>
    </tr>
  ));

  return (
    <>
      <Head>
        <title>Mutluluk Endeksi | User List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DashboardLayout>
          <Card withBorder shadow="sm" radius="md">
            <Card.Section withBorder inheritPadding py="xs">
              <Group position="apart">
                <Text weight={500}>User List</Text>
              </Group>
            </Card.Section>
            <Card.Section mt="sm">
              <ScrollArea style={{ width: '100%' }}>
                <Table striped highlightOnHover withBorder withColumnBorders>
                  <caption>User List</caption>
                  <thead>{ths}</thead>
                  <tbody>{rows}</tbody>
                  <tfoot>{ths}</tfoot>
                </Table>
              </ScrollArea>
            </Card.Section>
            <Card.Section>
              <Center w="100%" p="30px">
                <Pagination page={activePage} onChange={setPage} total={10}></Pagination>
              </Center>
            </Card.Section>
          </Card>
        </DashboardLayout>
      </main>
    </>
  )
}
