import {
  Anchor,
  Avatar,
  Breadcrumbs,
  Card,
  Center,
  Container,
  Flex,
  Group,
  Pagination,
  ScrollArea,
  Table,
  Text,
  useMantineTheme,
} from "@mantine/core";
import { useEffect, useState } from "react";

import DashboardLayout from "../../components/layout/DashboardLayout";
import Head from "next/head";
import { User } from ".prisma/client";
import axios from "axios";

export default function UserList() {
  const theme = useMantineTheme();
  const items = [
    { title: "Home", href: "/" },
    { title: "User List", href: "/user" },
  ].map((item, index) => (
    <Anchor href={item.href} key={index}>
      {item.title}
    </Anchor>
  ));

  const ths = (
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Email</th>
      <th>Email Verified</th>
      <th>Image</th>
      <th>CreatedAt</th>
      <th>UpdatedAt</th>
    </tr>
  );

  const [users, setUsers] = useState([]);
  const [activePage, setPage] = useState(1);
  const [pageCount, setPageCount] = useState(1);

  const getData = async () => {
    const { data } = await axios.get("/api/users", {
      params: {
        page: activePage,
        limit: 10,
      },
    });
    setUsers(data.data);

    setPageCount(data.pagination.pageCount);
  };

  useEffect(() => {
    getData();
  }, [activePage]);

  const rows = users.map((element: User) => (
    <tr key={element.id}>
      <td>{element.id}</td>
      <td>{element.name}</td>
      <td>{element.email}</td>
      {/* @ts-ignore */}
      <td>{new Date(element.emailVerified).toLocaleDateString()}</td>
      <td>
        <Avatar src={element.image} radius="xl" alt="it's me" />
      </td>
      <td>{new Date(element.createdAt).toLocaleDateString()}</td>
      <td>{new Date(element.updatedAt).toLocaleDateString()}</td>
    </tr>
  ));

  return (
    <>
      <Head>
        <title>Mutluluk Endeksi | User List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DashboardLayout>
          <Container
            fluid
            h="50px"
            pb="20px"
            bg={theme.colors.dark[6]}
            mb="md"
            style={{
              borderRadius: "15px",
              borderBottom: "2px solid #035",
              boxShadow: "0 0 10px 0 rgba(0,0,0,0.8)",
            }}
          >
            <Flex
              mih="70px"
              gap="md"
              justify="flex-start"
              align="center"
              direction="row"
              wrap="wrap"
            >
              <Breadcrumbs c={theme.colors.blue[1]} separator="→">
                {items}
              </Breadcrumbs>
            </Flex>
          </Container>
          <Card
            withBorder
            shadow="sm"
            radius="md"
            bg={theme.colors.dark[5]}
            style={{
              borderRadius: "15px",
              boxShadow: "0 0 10px 0 rgba(0,0,0,0.8)",
              borderBottom: "3px solid #050",
            }}
          >
            <Card.Section withBorder inheritPadding py="xs">
              <Group position="apart">
                <Text weight={500}>User List</Text>
              </Group>
            </Card.Section>
            <Card.Section mt="sm">
              <ScrollArea style={{ width: "100%" }}>
                <Table striped highlightOnHover withBorder withColumnBorders>
                  <caption>User List</caption>
                  <thead>{ths}</thead>
                  <tbody>{rows}</tbody>
                  <tfoot>{ths}</tfoot>
                </Table>
              </ScrollArea>
            </Card.Section>
            <Card.Section>
              <Center w="100%" p="30px">
                <Pagination
                  page={activePage}
                  onChange={setPage}
                  total={pageCount}
                ></Pagination>
              </Center>
            </Card.Section>
          </Card>
        </DashboardLayout>
      </main>
    </>
  );
}
