import {
  Anchor,
  Breadcrumbs,
  Container,
  Flex,
  Grid,
  Text,
  useMantineTheme,
} from "@mantine/core";
import { useEffect, useState } from "react";

import DashboardLayout from "../components/layout/DashboardLayout";
import DataCount from "../components/Dashboard/DataCount";
import Head from "next/head";
import axios from "axios";

export default function Home() {
  const theme = useMantineTheme();
  const items = [{ title: "Home", href: "/" }].map((item, index) => (
    <Anchor href={item.href} key={index}>
      {item.title}
    </Anchor>
  ));

  const [userCount, setUserCount] = useState(0);
  const [deviceCount, setDeviceCount] = useState(0);
  const [emotionCount, setEmotionCount] = useState(0);

  useEffect(() => {
    const getData = async () => {
      const { data: userData } = await axios.get("/api/stats/user");
      const { data: deviceData } = await axios.get("/api/stats/device");
      const { data: emotionData } = await axios.get("/api/stats/emotion");
      setUserCount(userData.count);
      setDeviceCount(deviceData.count);
      setEmotionCount(emotionData.count);
    };
    getData();
  }, []);

  return (
    <>
      <Head>
        <title>Mutluluk Endeksi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DashboardLayout>
          <Container
            fluid
            h="50px"
            bg={theme.colors.dark[6]}
            mb="md"
            style={{
              borderRadius: "15px",
              borderBottom: "2px solid #035",
              boxShadow: "0 0 10px 0 rgba(0,0,0,0.8)",
            }}
          >
            <Flex
              mih={50}
              gap="md"
              justify="flex-start"
              align="center"
              direction="row"
              wrap="wrap"
            >
              <Breadcrumbs separator="→">{items}</Breadcrumbs>
            </Flex>
          </Container>
          <Container
            fluid
            bg={theme.colors.dark[5]}
            style={{
              borderRadius: "15px",
              boxShadow: "0 0 10px 0 rgba(0,0,0,0.8)",
              borderBottom: "3px solid #050",
              padding: "35px",
            }}
          >
            <Grid gutter={10} gutterXs="md" gutterMd="xl" gutterXl={25}>
              <DataCount title="User" count={userCount}></DataCount>
              <DataCount title="Device" count={deviceCount}></DataCount>
              <DataCount title="Emotion" count={emotionCount}></DataCount>
            </Grid>
          </Container>
        </DashboardLayout>
      </main>
    </>
  );
}
