import Head from 'next/head'
import DashboardLayout from '../components/layout/DashboardLayout'
import { Text } from '@mantine/core'

export default function Home() {
  return (
    <>
      <Head>
        <title>Mutluluk Endeksi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DashboardLayout>
          <Text>Dashboard Home</Text>
        </DashboardLayout>
      </main>
    </>
  )
}
